---
title: 5th Annual Deil S. Wright Symposium on Friday, March 9, 2018
date: "2017-04-20"
description: "The Section on Intergovernmental Administration and Management (SIAM) invites scholars and practitioners to submit proposals for papers to be presented at the 5th Annual Deil S. Wright Symposium. The symposium honors the career and contributions of Professor Deil S. Wright, a charter member of SIAM who remained active until his passing in 2009. The Wright Symposium will be a preconference event held on Friday, March 9, 2018 at the national conference of the American Society for Public Administration (ASPA) in Denver, Colorado."
categories:
    - call-for-papers
---

The Section on Intergovernmental Administration and Management (SIAM) invites scholars and practitioners to submit proposals for papers to be presented at the 5th Annual Deil S. Wright Symposium. The symposium honors the career and contributions of Professor Deil S. Wright, a charter member of SIAM who remained active until his passing in 2009. The Wright Symposium will be a preconference event held on Friday, March 9, 2018 at the national conference of the American Society for Public Administration (ASPA) in Denver, Colorado.

The 2018 symposium will explore state-local relations in the United States.  Wright’s classic textbook Understanding Intergovernmental Relations acknowledged the importance of state-local relations within our federal system.  Wright commented on many dimensions of this relationship including local boundaries and systems of governance, revenue systems, mandates and regulation, and administrative coordination.  State-local relations are sometimes characterized by conflict, sometimes in competition, but often through partnership and collaboration.  The 2018 Wright Symposium will feature empirical studies that provide insight into the character, quality and variety of state-local relations today.  The Symposium seeks proposals on all aspects of state-local relations.  Questions to engage may include, but are not limited to, the following:

* To what extent are today’s state-local relations characterized by conflict, competition, cooperation, or something else?
* What explains variation in the character of state-local relations across states and across policies, and is the pattern of variation changing?
* What is the future for emergency manager laws and state take-overs of local governments and services, e.g. education?
* How has political polarization affected state preemption of local authority in different policy areas, and what explains variation in local authority across the states?
* What should public managers learn from recent failures, e.g. the crisis in Flint, Michigan, and successes in state-local relations?
* What approaches are states taking steps to foster local innovation and experimentation in economic development, education, environmental policy, social policy, or other fields?
* In what ways are states engaging in new forms of cooperation with local governments and metropolitan regions to advance job training and economic development?
* As the federal regulatory climate shifts, how are different states responding and what are the consequences for their interactions with local governments?
* In which policy areas is Republican control of the national government most likely to result in new devolutions to the states, and perhaps second-order devolution to local governments?
* Is the current structure of administrator and elected official involvement in intergovernmental relations similar to that described by Deil Wright in 1990, or have patterns of intergovernmental relations changed with the evolving importance of policy networks?

The Deil S. Wright Symposium has become a premier venue for sharing intergovernmental relations research.  Proposals should explain how the author(s) advance our theoretical understanding of state-local relations and federal systems.  Successful proposal will seek insight through new data, path-breaking methods, and critical questioning of existing knowledge.

The organizers of the 2018 Wright Symposium intend to prepare an edited volume based upon the symposium theme.  Papers from the symposium may be included after careful peer review.  Submit your proposal before August 1, 2017.  Proposals should be sent by email to Russ Hanson (<hansonr@indiana.edu>) and Eric Zeemering (<zeem@niu.edu>).  The proposal should include contact information for all authors, the paper title, a proposal of 500 words or less, and an explanation of how the research relates to the theme outlined in this call for papers.  For accepted proposals, complete draft papers for the symposium should be submitted by January 1, 2018.  The editors will review the work and provide feedback before the symposium.  This will also provide an opportunity to solicit discussants for the symposium sessions.  We look forward to your participation in the 2018 Deil S. Wright Symposium at the ASPA Conference.
