---
title: "Deil S. Wright Symposium"
date: "2016-03-18"
description: "Symposium program information. This years symposium theme is Intergovernmental Management in Transition."
author: "" 
toc: true
categories:
    - symposium
---

The Section on Intergovernmental Administration and Management (SIAM) invites ASPA members to attend the 2016 Deil S. Wright Symposium at the 2016 ASPA national conference in Seattle. The symposium honors the career and contributions of Professor Deil S. Wright, who was a charter member of SIAM and remained active until his passing in 2009. The all-day meeting on Friday, March 18 will feature cutting edge research on local governance and intergovernmental management by outstanding doctoral candidates and junior scholars, collaborating with faculty members, as well as a panel discussion on the Section’s mission. The theme of the symposium is “Intergovernmental Management in Transition” Following is the preliminary agenda.

## Intergovernmental Management in Transition

### Welcome 
8:30-8:45

Richard Feiock and Carl Stenberg

### Local Governance and Intergovernmental Management Research
8:45-10:00 

#### The Rise of Specialized Governance in Federalism: Links between Local Autonomy and Special Districts among States
Yu Shi, University of Illinois at Chicago

#### The Dynamics of Interorganizational Risk Management Networks: Following the 2015 South Korea MERS Response  
KyungWoo (John) Kim, University of North Texas            

#### Policy Abandonment at Multiple Levels of Government: Understanding Why State and Local Governments Abandon Economic Development Incentives
Eric Stokan, George Washington University

#### External and Internal Influences on Local Governments to Design Comprehensive Sustainability Programs
Hyungjun Ji, Arizona State University

#### Why Do Local Leaders Cooperate Across Boundaries? Results from a National Survey Experiment on Mayors and Councilors
Meghan Rubado, Temple University

### Break
10:00-10:15 

### Discussion of Panel 1 Papers
10:15-11:00 

Discussants include editors of State and Local Government Review, Public Administration Review, Urban Affairs Review

### What Future for SIAM?  Exploring and Adjusting the Mission of ASPA’s Intergovernmental Section
11:00-12:30 

This roundtable features leading scholars and practitioners who served on the committee to review the recent SIAM mission change and make implementation recommendations.  Eric Zeemering will present results of the survey of SIAM members the committee conducted and panel members will provide their thoughts, assessments, and ideas in a dialogue with the other panelists and the audience.

Participants
: Eric Zeemering, Northern Illinois University (Chair)
: Ed Benton, University of South Florida
: David Miller, University of Pittsburgh
: David Warm, Executive Director, Mid-America Regional Council

### Lunch Break
12:30-1:30  

### Local Governance and Intergovernmental Management Research
1:30-3:00  

#### Bottom-up Federalism: An Examination of U.S. Local Governments’ Climate Change Policy
Benoy Jacob, University of Colorado, Denver, Brian Gerber, Arizona State University, Sam Gallaher, University of Colorado, Denver

#### Equipment Sharing Among Local Governments
Daniel D. Wendt, Bowling Green State University

#### Empathy and Ethics in Public Servants: The Role of Public Administration Education in Developing Competencies for Collaborative Governance
Mariglynn Edlins and Stephanie Dolamore, University of Baltimore

#### Can You Put Food on the Table? Redefining Poverty in America
Maureen Berner and Alexander Vazquez, University of North Carolina at Chapel Hill

Discussant
: John Kincaid, Layafette University

### Break
3:00-3:15  

### Public Administration and Providing and Managing Collaborative and Environmental Programs in the New Era
3:15-4:45

#### Providing Public Services in a Networked and Collaborative Environment
David K. Hamilton, Texas Tech University

#### The Municipal Governance of Sustainability: Climate Change, Polycentricity, and Public Administration
Dennis Patterson and Robert E. Forbis, Jr., Texas Tech University

#### Determinants of Change and Innovation in U.S. Local Governments Natural Hazard Management Practices
Brian Gerber, Arizona State University

#### The Conflicted Role of Professional Managers: Help Guild or Insulate from the Metropolitan Region
David Miller, University of Pittsburgh

Discussant
:Beverly Cigler, Penn State Harrisburg

### Wrap-Up 
4:45-5:00

Richard Feiock and Eric Zeemering