---
title: "State & Local Government Review"
page-layout: full
sidebar: false
toc: false
---

[*State and Local Government Review*](https://journals.sagepub.com/home/slg) is the premier journal of scholarship, practical engagement, and discourse on state and local governance. The journal explores subnational governance and administration in federal and multilevel systems around the globe.

*State and Local Government Review* provides “an outlet for research which can be applied to the practical problems of state and local governments throughout the country.” Established in 1968 at the Georgia Government Review by the Carl Vinson Institute of Government at the University of Georgia, the journal provides a “national interchange of ideas for practitioners, academics, and institutes of government.” *State and Local Government Review* is the official journal of the Section on Intergovernmental Administration and Management (SIAM) of the American Society for Public Administration. Like the Vinson Institute, SIAM has an interest not only in state and local government, but also in the effective interaction among public officials in a federal system. It seeks to foster the dissemination of information about research and experience that contributes to the understanding and improvement of the intergovernmental system (SAGE Publishing).

Editors
: Kimberly Nelson, University of North Carolina – Chapel Hill, USA
: Eric Zeemering, University of Georgia, USA
