---
title: Annual SIAM Awards at ASPA 2023
date: "2023-04-26"
description: "At the recent virtual ASPA conference, SIAM awarded the following awards."
categories:
    - announcements
---

At the recent virtual ASPA conference, SIAM awarded the following:

### Donald C. Stone Awards

Distinguished Scholar Award 
: Kathleen Hale

Professor Hale’s award recognizes her significant scholarly contributions to intergovernmental relations, including her impactful scholarly and applied work on election administration and her ongoing leadership at Auburn University.

Best Student Paper Award
: Shuwen Zhang

University of Illinois Chicago doctoral candidate Shuwen Zhang is recognized for her excellent paper, titled: “How Does Cities’ Engagement Affect the Function of Regional Intergovernmental Organizations (RIGO’s) in Metropolitan Areas?” which was presented at ASPA 2022 in Jacksonville.

Practitioner Award
: Mark Fowler

Mark Fowler’s award recognizes his significant contributions to inter-governmental relations. Mark’s nomination highlighted his wide-ranging work in the Chicago Metropolitan Area and the State of Illinois; in particular, and his current work as the Executive Director of the Northwest Municipal Conference.

**SIAM Legacy Award**

This award recognizes Professor Carl Stenberg’s long-standing work on intergovernmental relations, his support and effort with the Deil Wright Symposium, and his contributions to both to the academic and professional sides of the field.

Congratulations to all the award recipients!