---
title: "Call for Nominations: SIAM Executive Committee Members (TWO)"
date: "2022-01-21"
description: "The Section on Intergovernmental Administration and Management (SIAM) of the American Society for Public Administration (ASPA) is seeking nominations for its Executive Committee. The SIAM Nominations Committee, chaired by Jayce Farmer and committee members Meghan Rubado, and Kendra Stewart, is seeking nominees for two Executive Committee members. Members of the committee will serve a three-year term (2022-2025). Please see our SIAM blog for the full list of current executive officers as well as the bylaws governing elections."
categories:
    - announcements
    - nominations
---

The Section on Intergovernmental Administration and Management (SIAM) of the American Society for Public Administration (ASPA) is seeking nominations for its Executive Committee. The SIAM Nominations Committee, chaired by Jayce Farmer and committee members Meghan Rubado, and Kendra Stewart, is seeking nominees for two Executive Committee members. Members of the committee will serve a three-year term (2022-2025). Please see our SIAM blog for the full list of current executive officers as well as the bylaws governing elections.

Executive committee members are actively engaged in the governance and work of the section, often contributing service to the Section’s committees and events.  Together with the Chair, Chair-Elect, Secretary and Treasurer, Executive Committee members help guide SIAM’s ongoing contributions to the fields of intergovernmental administration and management.  The Chair facilitates the work of the section, chairs executive committee meetings and business meetings, and serves as a primary channel of communication with ASPA.

Please submit your nominations for two Executive Committee members to Jayce Farmer (jayce.farmer@unlv.edu) on or before January 31, 2022.

The Nominations Committee will share a slate of nominees with the SIAM membership by February 4, 2022. After this, the Nominating Committee will receive additional nominations through membership petitions between February 4 and February 18, 2022.  Additional nominations during the petition period must be signed by 25 members of SIAM and accompanied by a statement from the nominee expressing interest and willingness to serve the Section.  Election ballots will be distributed to the membership after February 18 and election results will be announced at the annual business meeting at the ASPA conference in March 2022.