---
title: "Deil S. Wright Symposium 2019 Call for Papers"
date: "2018-07-23"
description: "The Section on Intergovernmental Administration and Management (SIAM) invites scholars and practitioners to submit proposals for papers to be presented at the 6th annual Deil S. Wright Symposium. The symposium honors the career and contributions of Professor Deil S. Wright, who was a charter member of the Section and remained active until his passing in 2009. The Wright Symposium will be held on March 8th, 2019 at the national conference of the American Society for Public Administration (ASPA) in Washington, DC."
categories:
    - call-for-papers
---

The Section on Intergovernmental Administration and Management (SIAM) invites scholars and practitioners to submit proposals for papers to be presented at the 6th annual Deil S. Wright Symposium. The symposium honors the career and contributions of Professor Deil S. Wright, who was a charter member of the Section and remained active until his passing in 2009. The Wright Symposium will be held on March 8th, 2019 at the national conference of the American Society for Public Administration (ASPA) in Washington, DC.

The theme of the all-day symposium is “Exploring the Federal in Federalism.” As the Federal regulatory environment is rapidly shifting in the US and abroad, important questions need to be addressed about: 1) state and local government responses to these shifts, and 2) the subsequent consequences to both/either the responses and/or the shifts?  It is unclear how extant theories of federalism can guide practitioners in navigating the current shifts in the political landscape.  Scholars of federalism, intergovernmental relations, intergovernmental management, and collaborative management can help improve federal systems by providing meta-analyses and synthesizing evidence in the field to inform practice. The 2018 Wright Symposium provides an excellent forum for doing so.

Proposed paper topics are invited that would help scholars and government professionals better understand what we have learned from the cumulative research on intergovernmental relations and management.  Papers are welcome to advance new research propositions, identify research gaps, or provide empirical evidence. The goal is to emphasize responses to Federal regulations or programs in the US or from a comparative perspective.  Topics might include, but are not limited to the:

Primary Themes:

* Value of intergovernmental institutions, such as the U.S. Advisory Commission on Intergovernmental Relations, or the White House Office on Intergovernmental Affairs;
* State and local strategies utilized as response to executive orders and regulatory changes that are perceived as contrary to state and local interests
* Development of collaborative intergovernmental competencies or skills by federal, regional, state, and local public managers;
* Impact of federal executive orders or presidential decrees on intergovernmental relations;

Major Related Themes:

* Design, accountability, and evaluation of intergovernmental grants and programs, including revenue sharing and fiscal equalization;
* Effectiveness of elected executives in managing intergovernmental relations in presidential and parliamentary federal systems;
* Effectiveness of intergovernmental, interjurisdictional, and inter-sectoral management networks;
* Impacts of federal mandates and conditions attached to federal grants-in-aid;
* Effectiveness of regulatory waivers;
* Impacts of court orders, consent decrees, and other judicial interventions into intergovernmental relations.

Proposals for the symposium should be submitted by email to Benoy Jacob (<Benoy.jacob@unlv.edu>) before October 1, 2018. *Proposals should be well developed and clearly demonstrate the ability to deliver a finished paper.* The Wright Symposium planning committee – John Kinkaid, Steve Percy, Benoy Jacob — will review proposals and make decisions by October 22.  Questions can be directed to committee members.  Please circulate this call for papers among interested colleagues.