---
title: "Call for Nominations: SIAM Chair Elect"
date: "2022-01-21"
description: "The Section on Intergovernmental Administration and Management (SIAM) of the American Society for Public Administration (ASPA) is seeking nominations for an executive officer. The SIAM Nominations Committee, chaired by Jayce Farmer and committee members Meghan Rubado and Kendra Stewart, is seeking nominees for the position of chair-elect. The chair-elect will serve a two year term (2022-2024) and then serve two years in the position of chair (2024-2026).  Please see our SIAM blog for the full list of current Executive Committee members as well as the bylaws governing elections."
categories:
    - announcements
    - nominations
---

The Section on Intergovernmental Administration and Management (SIAM) of the American Society for Public Administration (ASPA) is seeking nominations for an executive officer. The SIAM Nominations Committee, chaired by Jayce Farmer and committee members Meghan Rubado and Kendra Stewart, is seeking nominees for the position of chair-elect. The chair-elect will serve a two year term (2022-2024) and then serve two years in the position of chair (2024-2026).  Please see our SIAM blog for the full list of current Executive Committee members as well as the bylaws governing elections.

Executive committee members are actively engaged in the governance and work of the section, often contributing service to the Section’s committees and events.  Together with the Chair, Chair-Elect, Secretary and Treasurer, Executive Committee members help guide SIAM’s ongoing contributions to the fields of intergovernmental administration and management.  The Chair facilitates the work of the section, chairs executive committee meetings and business meetings, and serves as a primary channel of communication with ASPA.

**Please submit your nominations for the Chair-Elect to Jayce Farmer (<jayce.farmer@unlv.edu>) on or before January 8, 2021.**

The Nominations Committee will share a slate of nominees with the SIAM membership by January 9, 2021. After this, the Nominating Committee will receive additional nominations through membership petitions between January 9 and February 9, 2021.  Additional nominations during the petition period must be signed by 25 members of SIAM and accompanied by a statement from the nominee expressing interest and willingness to serve the Section.  Election ballots will be distributed to the membership after February 15 and election results will be announced at the annual business meeting at the virtual ASPA conference in April 2021.