---
title: "Call for Papers: SIAM-SLGR Joint ASPA Panel Featuring Graduate Student Research"
date: "2022-10-13"
description: "The Section on Intergovernmental Administration and Management (SIAM), in collaboration with State and Local Government Review (SLGR), invite current Ph.D students to submit proposals for papers to be presented at the 2023 American Society for Public Administration (ASPA) conference (virtual, March 20-24)."
categories:
    - call-for-papers
---

The Section on Intergovernmental Administration and Management (SIAM), in collaboration with State and Local Government Review (SLGR), invite current Ph.D students to submit proposals for papers to be presented at the 2023 American Society for Public Administration (ASPA) conference (virtual, March 20-24).

**Among the goals of the 2023 SIAM-SLGR collaboration panel are:**

1. Provide an opportunity for Ph.D students to present their current work on subjects that are of interest to SIAM members
2. Provide a space for new conversations between scholars, students, and practitioners of public administration who may not be in regular dialogue with one another
3. Facilitate feedback on student work

**Potential paper themes may include:**

* Current or emerging trends in intergovernmental management and governance
* Contemporary trends in the administration of major state or local policies
* Impact of political institutions, political behavior, or recent economic and demographic shifts on intergovernmental policy and management.
* Impact of changes in policy on state and local governments and their relations
* Domestic or international policy areas involving intergovernmental relations and associated management tools and strategies

**Submission Guidelines**

Individual Paper Proposals. The committee welcomes individual paper proposals of 400 words or less. Proposed papers may feature theoretical, qualitative, or quantitative research.  The program committee may alter or remove individual papers that do not meet review criteria or to add an individual paper submission that fits well with the objectives of the SIAM-SLRG joint panel.

**Submission Process**

Proposals for the panel should be submitted by email to Chris Hawkins ([christopher.hawkins@ucf.edu](mailto:christopher.hawkins@ucf.edu)) by November 1, 2022. We welcome proposals from student members and nonmembers of SIAM.