---
title: "Charter & Bylaws (as granted by ASPA)"
page-layout: full
sidebar: false
toc: true
#toc-title: Contents
toc-location: right
#toc-depth: 4
---

The American Society for Public Administration recognizes the development of specialized areas of interest within its membership as important to the advancement of the aims and purposes of the Society. Accordingly, it has granted and approved the following Charter and Bylaws for the Section on Intergovernmental Administration and Management. These are subject to the Constitution and Bylaws of the Society and to official Society policies governing the creation, evaluation, and termination of sections.

## ARTICLE I. Name and Purpose

**Section 1. Name:** This organization shall be known as the Section on Intergovernmental Administration and Management (SIAM) of the American Society for Public Administration.

**Section 2. Purpose:** The Section serves as a forum for the study, understanding, and improvement of federal systems and other forms of intergovernmental relations wherein national, state, and local governments address policy and management issues.

Provide a national forum for activities, publication and research of academicians and practitioners in the area of interstate and interlocal intergovernmental administrative and management issues, systemic concerns of the grant-in-aid system, and regional, state, and local problems and needs unique to the intergovernmental system.

**Section 3.**

This Section is organized for the professional and educational purposes of: exclusively charitable and educational purposes within the meaning of Section 501(c)(3) of the Internal Revenue Code of 1986, as now in effect or as may hereafter be amended (“Code”). Without limiting the generality of the foregoing, such purposes include the following:

(a) Advancing the science, processes, and art of public administration.
(b) Advancing the equality of opportunity of all persons through public administration.

In furtherance of its exclusively charitable and educational purposes, the Section shall have all general powers of an unincorporated association, together with the power to solicit and accept grants and contributions for such purposes.

## ARTICLE II. Activities

**Section 1.** SIAM may undertake the following activities which are not necessarily inclusive or mandatory:

**General:**

1. Serve as a recognized national and regional focal point and spokesperson for intergovernmental administrative and management related developments in education, training and research.
2. Identify major intergovernmental management needs, problems, and opportunities inherent in the structure of the American federal system.
3. Identify and promote the use of information sources and material which constitute the state of the art of intergovernmental management issues.
4. Provide a forum for the exchange of views, information, and research on intergovernmental administrative and management issues, federal, state, and local management capacity development, grants-in-aid, and related rule and regulation changes, etc.
5. Provide a forum for discussion, research, and documentation of challenges and operations related to interstate and interlocal relations.
6. Serve as a stimulus for enhancing the effectiveness of the intergovernmental system through the exploration, development, and testing of capacity building models designed to respond to state and local deficiencies and needs.
7. Formulate program/policy positions on intergovernmental issues and problems of national, regional, state, or local interest and concern.
8. Encourage and sponsor intergovernmental related research and state-of-the-art developments through panels/presentations at ASPA, or related professional association, regional and national conferences.
9. Cooperate with other ASPA organizational units (sections, chapters) on program issues of mutual concern related to the intergovernmental system.

**Training and Development:**

1. Develop training packages (papers, reports, manuals, recordings, and video tapes, etc.) integrating advances in the area of cooperative federal, state, and local program and technology development and implementation.
2. Promote the incorporation of intergovernmental projects into on-going training and educational programs at universities and at all levels of government and in related professional associations.
3. Sponsor workshops and seminars in cooperation with related ASPA sections on functional issues where intergovernmental management and administration is key to program effectiveness.

**Publications:**

1. Identify topics which should be included in the literature on intergovernmental coordination, cooperation, and management issues including, but not limited to, conference papers, articles, and books, and promote and encourage the publication of these sources.
2. Promote the publication of the section newsletter, occasional papers, or symposium of PAR or related journals on management capacity building in the context of intergovernmental policy management assistance or program administration and management from an intergovernmental perspective.
3. Support the work of the section-sponsored journal, State and Local Government Review. This may include financial support, advice to the editor, coordination of special symposium, or other forms of support at the discretion of the board.

**Research:**

1. Encourage section member research efforts related to intergovernmental administration and management.
2. Explore and develop research projects for funding by private foundations and governmental agencies.
3. Encourage federal, regional, state, and local research on intergovernmental administrative or management needs and interstate and interlocal concerns.
4. Assist in securing public agency funding support for section member research or special projects in the development and/or testing of systems, administrative tools or needs assessments, or development of course or curriculum materials related to the understanding or betterment of the Federal grant-in-aid system or intergovernmental infrastructure supporting the system.

**Section 2. Annual Report:**

SIAM shall prepare and submit a written annual report on its activities to the ASPA National Council.

## ARTICLE III. Membership

**Section 1.**

Membership in SIAM shall be open to all ASPA members who desire active association with the Section and who pay the enrollment fee and the annual dues.

**Section 2.**

Members shall have the right to:

* Hold office in SIAM
* Vote for elective officers
* Receive SIAM publications
* Participate in all SIAM activities
* Receive such benefits and opportunities as are available through the Section

## ARTICLE IV. Officers and Their Responsibilities

**Section 1.**

The officers of SIAM shall be the Chairperson, Chairperson-elect, immediate Past-Chairperson, and nine (9) members of the board. The term of the Chairperson and Chairperson-elect shall be one (2) year term.  The Chairperson-elect will assume the office of Chair upon the conclusion of the incumbent Chairperson’s two year term.  The nine (9) members will serve staggered three-year (3) terms. These elective officers constitute the SIAM Executive Committee.  The Chairperson-elect and members of the board will be elected by the membership as outlined in the procedures in Article V.

Any vacancies on the Executive Committee of less than one (1) year will be appointed by Chairperson, with the approval of the Executive Committee for the unexpired term of office.

**Section 2.**

The ASPA Executive Director or his/her designate shall serve as ex-officio member of the Executive Committee.

**Section 3.**

In consultation with the Executive Committee, the Chairperson appoints the Newsletter Editor, and special committees or task forces. With the approval of the Executive Committee, the Chairperson may appoint a Treasurer, Secretary and Membership Chair for the Section. The Treasurer, Secretary, Newsletter Editor and Membership Chair shall also serve on the Executive Committee. These officers may be selected among section members outside of the Executive Committee.

**Section 4.**

The Executive Committee is responsible for the overall performance and functioning of SIAM. Among its responsibilities will be the following:

1. Determining section dues, subject to approval by the ASPA National Council.
2. Approving section annual programs and budget.
3. Adopting positions on issues of relevance to section concerns.
4. Accepting donations, grants, and contracts for the section, subject to ASPA policy regarding this matter.
5. Serving on committees and/or Task Forces as deemed necessary by the Chair, or Executive Committee as a whole.
6. Decisions shall be taken by majority vote; in case of tie, the Chairperson’s vote shall prevail.

The Chairperson’s responsibilities will include: providing leadership to the Section; representing the Section; chairing the Executive Committee; presiding at section meetings; signing correspondence; supervising implementation of section programs and budget.

## ARTICLE V. Elections

**Section 1.**

All members of the Section on Intergovernmental Administration and Management shall have the right to vote for, and to be nominated to, SIAM elective off ices.

**Section 2.**

The following election procedures shall be followed:

1. The Chairperson will appoint a Nomination Committee of three (3) members at least four (4) months prior to the annual Section meeting.
2. The Nominating Committee will receive nominations and publish a slate of candidates at least three (3) months prior to the annual Section meeting.
3. The Nominating Committee receive additional nominations from the petition process up to two (2) months prior to the annual Section meeting; such additional nominations to be signed by 25 members of SIAM and accompanied by a statement from the nominee expressing interest and willingness to serve the Section.
4. Ballots will be distributed to the membership at least one (1) month prior to the annual Section meeting. Voting may occur through the distribution of a paper ballot, through email, or through the use of another online instrument. The method of voting will be announced to the membership when the slate of candidates is announced.
5. New officers will be announced at the annual Section meeting.
6. Newly elected officers will assume office at the beginning of the annual Section meeting, to be held in conjunction with the ASPA National Conference.

## ARTICLE VI. Finances and Administration

**Section 1. Grants and Contracts:**

The ASPA National Council is responsible for approving, receiving, and auditing grants or contracts solicited by SIAM. As a tax exempt non-profit educational organization, ASPA is qualified to receive designated donations for the programs and activities sponsored by SIAM.

An overhead charge may be applied to all grants and contracts administered by ASPA.

**Section 2. Accounting Models:**

SIAM dues, enrollment fees and other revenues shall be collected and allocated quarterly to the Section by the ASPA Executive Director. The Section may opt to maintain its own financial records, checking and savings accounts, and be responsible for all financial transactions. In this case, it shall follow such accounting procedures as may be specified by ASPA’s Finance and Administration Committee and shall furnish an annual audit report to the National Council.

The section may purchase services from any vendor, including the ASPA National Office.

For the section, the budget year shall be the calendar year.

All expenditures must be reviewed and approved by the Chairperson, Chairperson-elect, and Treasurer and will be reported to the membership at the annual meeting.

**Section 3. Change of Accounting Model:**

SIAM may opt to change the accounting model by decision of the Executive Committee. For the change to take effect in the following year, the ASPA Executive Director shall be notified of the desire for change at least two (2) months before the new fiscal year begins.

**Section 4. Administration and Support:**

SIAM shall be responsible for the administration and support of its programs and activities. A budget and work program shall be prepared and approved by the Executive Committee every year for the coming year. Section responsibilities include, but are not limited to the following: scheduling section meetings and taking the minutes thereof; running Section elections; organizing program sessions during ASPA’s national and regional conferences; preparing and distributing section brochures; producing newsletters and publications; planning and executing all workshops; developing and conducting membership campaigns; as well as maintaining meeting and financial records.

The ASPA Executive Director shall provide SIAM with periodic membership rosters and labels, ASPA handbooks and membership brochures and application forms, ASPA officers’ newsletters, membership reports, and any other appropriate information.

In addition, the ASPA Executive Director shall organize workshops on Section administration and development and shall provide coordination and linkage between SIAM and other ASPA organizational components.

## ARTICLE VII. Meetings

**Section 1. General Membership Meetings**

A general membership meeting of SIAM will be held at least annually at each ASPA National Conference, and may be held elsewhere at other times of the year.

**Section 2. Executive Committee Meetings**
The SIAM Executive Committee shall meet at each ASPA National Conference and at such other times as may be conveniently arranged by the Chairperson.  The Executive Committee must hold at least one meeting between regular annual meetings, and this meeting should be conducted through conference call or another electronic medium to allow maximum participation of executive committee members.

**Section 3. Other Meetings**

The Executive Committee may arrange for regional special, or other meetings of SIAM or its committees at such times and places as appropriate. Funding for all meetings will be limited to amounts budgeted, unless special additional funds are made available from other sources.

## ARTICLE VIII. Amendments

**Section 1.**

Substantive changes in this Charter and Bylaws may be voted upon by the Section membership at the annual Section meeting or through mail ballot and shall then be referred to the National Council. If interim action appears necessary, the SIAM Executive Committee may submit amendments to the ASPA National Council.

**Section 2.**

Clarifying changes which are in accord with policies of the National Council and which the Executive Director of ASPA and the Section Chairperson consider desirable may be made in this Charter and Bylaws from time to time without referral to the National Council. Such changes shall then be referred to the SIAM membership for information with reasons for changes.

**Section 3.**

Consistent with inclusion of this Section in the group federal income tax exemption ruling of the American Society for Public Administration (identified by the Internal
Revenue Service as Group Exemption Number 3155), all amendments to the Section Charter which may be made from time to time shall be submitted to the American Society for Public Administration for its approval.

## Article IX.

**Section 1.**

No part of the net earnings of the Section shall inure to the benefit of, or be distributable to any director or officer of the Section, or any other private person, except that the Section shall be authorized and empowered to pay reasonable compensation for services rendered to or for the Section and to make payments and distributions in furtherance of the purposes set forth hereinabove.

**Section 2.**

No substantial part of the activities of the Section shall be the carrying on of propaganda, or otherwise attempting to influence legislation (except as otherwise permitted by Section 501(h) of the Code), and the Section shall not participate in, or intervene in (including the publishing or distribution of statements concerning) any political campaign on behalf of or in opposition to any candidate for public office. Notwithstanding any other provision of these articles, the Section shall not carry on any other activities not permitted to be carried on

(a) by an organization exempt from federal income tax under Section 501(c)(3) of the Code, or
(b) by an organization, contributions to which are deductible under Section 170(c)(2) of the Code.

**Section 3.**

In the event of dissolution or final liquidation of the Section, after paying or making provision for the payment of all of the liabilities and obligations of the Section and for necessary expenses thereof, all of the remaining assets and property of the Section shall be distributed to the American Society for Public Administration provided it remains organized and operated exclusively for charitable or educational purposes as shall at the time qualify as an exempt organization under Section 501(c)(3) of the Code, and if not, to an organization which does so qualify. In no event shall any of such assets or property be distributed to any director or officer or to any private individual.

**Section 4.**

The fiscal year of the Section shall end in the month of December. The employer identification number assigned by the Internal Revenue Service to this Section is: EIN 52-1203980

Adopted by the organization meeting of (date).

ORIGINAL CHARTER ADOPTED BY THE SIAM MEMBERSHIP AT ITS ANNUAL MEETING ON APRIL 3, 1979 AT THE LORD BALTIMORE HOTEL, BALTIMORE AND APPROVED BY THE ASPA NATIONAL COUNCIL AT ITS MEETING ON APRIL 4, 1979 AT THE BALTIMORE HILTON HOTEL, BALTIMORE.

REVISIONS ADOPTED BY THE SIAM EXECUTIVE BOARD AND THE SIAM MEMBERSHIP IN NOVEMBER, 2000.

REVISIONS ADOPTED AT THE ANNUAL MEETING OF THE SIAM MEMBERSHIP ON MARCH 8, 2015 IN CHICAGO, ILLINOIS.

REVISIONS ADOTPED AT THE ANNUAL MEETING OF THE SIAM MEMBERSHIP ON MARCH 19, 2016 IN SEATTLE, WASHINGTON.