---
title: Call to Participate in Encyclopedia of Local and Regional Government and Politics
date: "2023-08-01"
description: "Ed Benton (University of South Florida), along with John Kincaid (Lafayette College), are preparing the Encyclopedia of Local and Regional Government and Politics to be published by Edward Elgar by 2025. We have a contract to produce this book. Because it is very important for scholars like you to have your work recognized and cited, please know that Elgar will submit all of our Encyclopedia entries to such citation services as Google Scholar and Scopus. We wish to include in the encyclopedia new and original articles on all pertinent topics/subject areas related to the existence and operation of local and regional governments around the world and their ensuing relevant politics, policies, programs, etc."
categories:
    - announcements
---

Ed Benton (University of South Florida), along with John Kincaid (Lafayette College), are preparing the Encyclopedia of Local and Regional Government and Politics to be published by Edward Elgar by 2025. We have a contract to produce this book. Because it is very important for scholars like you to have your work recognized and cited, please know that Elgar will submit all of our Encyclopedia entries to such citation services as Google Scholar and Scopus. We wish to include in the encyclopedia new and original articles on all pertinent topics/subject areas related to the existence and operation of local and regional governments around the world and their ensuing relevant politics, policies, programs, etc.

As someone who regularly teaches and writes about this subject matter, we hope you will consider being part of this monumental publication.

There are three ways you can contribute to this encyclopedia. First, you can send us pertinent topics or subject areas that should be covered in the encyclopedia. (An initial list of topics is provided below.) Second, you can suggest topics or subject areas on which you would like to write one or more entries. Third, you can provide us names of, and contact information for, scholars who could contribute to the volume; please also provide their subject-matter expertise or specific topics they are qualified to write on. This volume has a global perspective and will, tentatively, cover many countries, including the United States, Canada, Mexico, Brazil, Argentina, Columbia, United Kingdom, France, Spain, Portugal, Belgium, Germany, Netherlands, Denmark, Italy, Switzerland, Austria, Romania, Poland, Czech Republic, Greece, Norway, Sweden, Finland, Hungary, Serbia, Bulgaria, Slovakia, Russia, Nigeria, South Africa, Ethiopia, Egypt, Kenya, Tanzania, Turkey, Iran, Iraq, Saudi Arabia, China, India, Pakistan, Bangladesh, Indonesia, and Australia.

We need to hear from you as soon as possible so we can finalize the topics and invite contributors in order to publish the encyclopedia in a timely manner so as to make the volume as current and relevant as possible to a wide and diverse international audience. You can contact Ed Benton at [jbenton@usf.edu](mailto:jbenton@usf.edu) and/or John Kincaid at [kincaidj@lafayette.edu](mailto:kincaidj@lafayette.edu).  We encourage you to contact us as soon as you see this notice. Thank you.