---
title: "2025 Deil S. Wright Symposium: Call for Proposals"
date: "2024-10-21"
description: "The Section on Intergovernmental Administration and Management invites scholars and practitioners to submit proposals for papers to be presented at the 8th annual Deil S. Wright Symposium. The symposium honors the career and contributions of Professor Deil S. Wright, who was a charter member of the Section and remained active until his passing in 2009. The Wright Symposium will be held at the national conference of the American Society for Public Administration in Washington, DC. The theme of the all-day 2025 Wright Symposium will be “New Administration, New Trends in Federalism.”"
toc: true
categories:
    - call-for-papers
---

The **Section on Intergovernmental Administration and Management (SIAM)** invites scholars and practitioners to submit proposals for papers to be presented at the 11th Annual Deil S. Wright Symposium. The symposium is a full day event that honors the career and contributions of Professor Deil S. Wright, a charter member of SIAM who remained active until his passing in 2009. The Wright Symposium will be held Friday, March 28, 2025, 8:00 a.m. – 5:00 p.m. during the national conference of the American Society for Public Administration (ASPA) in Washington, D.C. 

The 2025 symposium will explore the theme “New Administration, New Trends in Federalism.”  This symposium will be held in the nation’s capital only a few months after the installation of a new administration at the federal level. This change will have implications for federalism at all levels of government. Wright’s classic textbook Understanding Intergovernmental Relations emphasized evolution and change in American federalism and intergovernmental relations over time. How might Wright describe current dynamics in our federal system? Actions at the federal level are bound to effect those at the state and local levels. Intergovernmental relations are sometimes characterized by conflict, sometimes by competition, but often through partnership and collaboration. The 2025 Wright Symposium will feature empirical studies that provide insight into the character, quality and variety of federalism today. The Symposium seeks proposals on all aspects of federalism.  

Questions to engage may include, but are not limited to, the following:

* To what extent are today’s intergovernmental relations characterized by conflict, competition, cooperation, or something else?
* What explains variation in the character of state-local relations across states and across policies, and is the pattern of variation changing?
* What should public managers learn from recent tensions between governments at different levels?
* What are the implications of new federal spending programs for policy implementation at the state and local level?
* How does the public view different levels of government and the relationships between them?

The Deil S. Wright Symposium has become a premier venue for sharing intergovernmental relations research. Proposals should explain how the research advances our theoretical understanding of intergovernmental relations. Successful proposal will seek insight through new data, path-breaking methods, and critical questioning of existing knowledge.

### Submission Process

Submit your proposal **before November 15, 2024**.  Proposals should be sent by email to Aaron Deslatte [adeslatt@iu.edu](mailto:adeslatt@iu.edu). The proposal should include contact information for all authors, the paper title, a proposal of 500 words or less, and an explanation of how the research relates to the theme outlined in this call for papers. 

We look forward to your participation in the 2025 Deil S. Wright Symposium at the ASPA Conference.
