---
title: "Deil S. Wright Symposium"
date: "2021-04-09"
description: "Symposium program information."
author: "" 
toc: true
categories:
    - symposium
---

### Introductions and Welcome
8:45–9:00AM

### The Future of Fiscal Federalism 
9:00–10:30AM

#### If Congress Can’t Budget, Can It Influence Intergovernmental Relations?
Nicholas Jacobs, Colby College

#### Fiscal Sustainability of Mexican Debt Decisions: Is Bad Behavior Rewarded? 
Carmina Jimenez Quiroga & Heidi Jane M. Smith, CENTRUS/Universidad Iberoamericana

#### Too Many Governments and Not Enough Government: Does Citizen Voice Restrain Government Growth?  
Yoon-Jung Choi, Syracuse University 

Discussant
: Paul Chalekian, University of Nevada, Reno

### Break
10:30–10:45AM


### Rethinking Models of Intergovernmental Relations
10:45AM–12:15PM

#### Overcoming dysfunctional integration through domestic administrative capacity building: a new approach to Europeanization   
Claudia Badulescu-Colfer, European University Institute  

#### National and Subnational Bureaucracies’ Capacity for Service Provision: A Human-Capital Approach to Decentralized Governance    
Ricardo A. Bello-Gomez, Indiana University 

#### Immigration Federalism in the U.S.: A New Theoretical Model
Sara Kuehlhorn Friedman, Portland State University
 
#### Intergovernmental Collaboration or Conflict? 
Matt Bagwell, Tarleton State University

Discussant
: TBA

### Lunch Break
12:15–1:15PM

### Studying and Practicing Intergovernmental Relations and Federalism Across Fields
1:15–2:45PM

#### Going Deep: Studying Charter Schools from the Bottom Up 
Carol Weissert and Matthew Uttermark, Florida State University

#### A Research Agenda for Federalism Studies
John Kincaid, Lafayette College

#### Using Wright’s ASAP Data from 1964-2008 to Study Federalism and Intergovernmental Relations:  New Data for Scholars and Practitioners
Jason Webb Yackee and Susan Webb Yackee, University of Wisconsin – Madison

Discussant
: TBA

### Wrap Up
2:45-3:00PM

