---
title: "2017 Deil S. Wright Symposium: Call for Proposals"
date: "2016-07-28"
description: "The Section on Intergovernmental Administration and Management (SIAM) invites scholars and practitioners to submit proposals for papers to be presented at the 4th annual Deil S. Wright Symposium. The symposium honors the career and contributions of Professor Deil S. Wright, who was a charter member of the Section and remained active until his passing in 2009. The Wright Symposium will be a preconference event held on Friday, March 17, 2017 at the national conference of the American Society for Public Administration (ASPA) in Atlanta, Georgia."
categories:
    - call-for-papers
---

The Section on Intergovernmental Administration and Management (SIAM) invites scholars and practitioners to submit proposals for papers to be presented at the 4th annual Deil S. Wright Symposium. The symposium honors the career and contributions of Professor Deil S. Wright, who was a charter member of the Section and remained active until his passing in 2009. The Wright Symposium will be a preconference event held on Friday, March 17, 2017 at the national conference of the American Society for Public Administration (ASPA) in Atlanta, Georgia.

The theme of the all-day symposium is “Evidence-Based Intergovernmental Management: Knowledge at Work.” It will focus on U.S. federalism and comparative federalism. Through decades of research on federalism and intergovernmental relations, public administration scholars have generated knowledge about effective governance and management in federal systems. While the cumulative lessons of this research may be familiar to some, they have not been discussed widely by scholars or used by professional public managers. Today, public officials are expected to take evidence-based approaches to policy design and implementation, and the record of research evidence about what has worked and what has failed to produce desired results would be an invaluable resource. Scholars of federalism, intergovernmental relations, intergovernmental management, and collaborative management can help improve federal systems by providing meta-analyses and synthesizing evidence in the field to inform practice. The 2017 Wright Symposium provides an excellent forum for doing so.

Proposed paper topics are invited that would help scholars and government professionals better understand what we have learned from the cumulative research on intergovernmental relations and management.  Papers are welcome to advance new research propositions, identify research gaps, or provide empirical evidence. The goal is to emphasize for public managers how evidence can be used to shape intergovernmental management practice.  Topics might include, but are not limited to the:

* Design, accountability, and evaluation of intergovernmental grants and programs, including revenue sharing and fiscal equalization;
* Development of collaborative intergovernmental competencies or skills by federal, regional, state, and local public managers;
* Effectiveness of elected executives in managing intergovernmental relations in presidential and parliamentary federal systems;
* Effectiveness of intergovernmental, interjurisdictional, and intersectoral management networks;
* Value of intergovernmental institutions, such as the U.S. Advisory Commission on Intergovernmental Relations, Council of Australian Governments, or the White House Office on Intergovernmental Affairs;
* Impact of federalism executive orders or presidential decrees on intergovernmetal relations;
* Impacts of federal mandates and conditions attached to federal grants-in-aid;
* Effectiveness of regulatory waivers;
* Diffusion of evidence-based practices horizontally across constituent units such as states, provinces, and cantons;
* Performance of regional governments and organizations, such as consolidated or amalgamated local governments, metropolitan governments, councils of governments, and city-states;
* Advantages and disadvantages of optional forms of local government;
* Consequences of litigation for the authority of public managers in intergovernmental programs;
* Impacts of court orders, consent decrees, and other judicial interventions into intergovernmental relations.
 
Proposals for the symposium should be submitted by email to Carl Stenberg (<stenberg@sog.unc.edu>) before October 1. Proposals should be well developed and clearly demonstrate the ability to deliver a finished paper. The Wright Symposium planning committee – Ann Bowman, John Kincaid, Michael McGuire, Eric Zeemering, and Carl Stenberg — will review proposals and make decisions by October 22.  Questions can be directed to committee members.  Please circulate this call for papers among interested colleagues.