---
title: "Deil S. Wright Symposium"
date: "2019-03-08"
description: "Symposium program information. This years symposium theme is Exploring the Federal in Federalism."
author: "" 
toc: true
categories:
    - symposium
---

The Section on Intergovernmental Administration and Management (SIAM) invites members of the American Society for Public Administration (ASPA) to attend the 6th annual Deil S. Wright Symposium. The symposium honors the career and contributions of Professor Deil S. Wright, who was a charter member of SIAM and remained active until his passing in 2009. The Wright Symposium will be held on March 8, 2019 at ASPA’s national conference in Washington, DC.

The theme of the all-day symposium is “Exploring the Federal in Federalism.” As the federal regulatory environment is rapidly shifting in the US and abroad, important questions will be addressed about: 1) state and local government responses to these shifts and 2) the subsequent consequences of both/either the responses and/or the shifts?

With these broad questions in mind, the symposium will include research on environmental federalism, intergovernmental collaboration, the role of local governments in regional systems, and a roundtable discussion on the implications of Trump and the mid-term elections on intergovernmental relationships. The 2019 Wright Symposium will provide a rich and lively forum for scholars and practitioners interested in intergovernmental issues. Following is a preliminary agenda (from 8:00 am to 5:00 pm).
   

## Morning Sessions

### Welcome

### The Role of Local Governments in U.S. and European Regional Governance

(with moderated discussion and Q&A)

### Break

### Environmental Federalism

(with moderated discussion and Q&A)

### Lunch Break
 
## Afternoon Sessions


### Intergovernmental Collaboration

(with moderated discussion and Q&A)

### Break

### Roundtable Discussion: The implications of Trump and the mid-term elections on intergovernmental relationships

### Wrap-Up 