---
title: "Center for the Study of Federalism Launches New Federalism Website"
date: "2018-06-21"
description: "The Center for the Study of Federalism USA (CSF) has launched its website–federalism.org — the first American website exclusively devoted to federalism. Winner of the prestigious Graphis gold award for its logo design and Gold Award from Educational Digital Marketing, federalism.org is the official CSF site and a clearinghouse for a wide range of federalism resources and information."
categories:
    - announcements
---

The Center for the Study of Federalism USA (CSF) has launched its website–federalism.org — the first American website exclusively devoted to federalism. Winner of the prestigious Graphis gold award for its logo design and Gold Award from Educational Digital Marketing, federalism.org is the official CSF site and a clearinghouse for a wide range of federalism resources and information.

Visit us at <www.federalism.org> to see...

* Applications and guidelines for research grants, teacher awards, and scholar awards.
* Full text of the updated encyclopedia, Federalism in America, previously published by Greenwood.
* Information and resources for students, such as a federalism timeline.
* Full text and commentaries of many U.S. founding documents, including state constitutions.
* All entries in our “State and Local Government Firsts that Changed America” project.
* CSF Archives, including its history, mission, biographies of CSF fellows and associates, and complete listings of its past activities and publications.
* Publius: The Journal of Federalism, its history, tables of contents, and a biography of its namesake.

Also...

Announcements, regularly updated, on federalism scholarship and scholarly events worldwide.
News on political and constitutional events affecting federalism worldwide.
Succinct analyses of federalism developments.

Get involved...

* Tell us how we can improve and further develop the website.
* Send us announcements on new books, articles, and conferences on federalism.
* Send us links to news events on federalism in the U.S. and elsewhere.
* Send us brief analyses of federalism developments anywhere in the world.
* Help us expand the reach of the website beyond U.S. federalism to federalism worldwide.

Contact us at <csf@federalism.org>.

CSF President, John Kincaid; Vice President, Stephen L. Schechter; Treasurer, Donald S. Lutz; Secretary, Joseph R. Marbach; Web Master, J. Wesley Leckrone; Encyclopedia Editor, Troy E. Smith; and Lance Cooper, News Editor.