---
title: "5th Annual Deil S. Wright Symposium"
date: "2018-03-09"
description: "Symposium program information. This years symposium theme is Local Government and the States: The Shifting Dynamics of State-Local Relations."
author: "" 
toc: true
categories:
    - symposium
---

## Local Government and the States: The Shifting Dynamics of State-Local Relations
### Welcome & Introduction
8:45 AM – 9:00 AM

Russ Hanson, Indiana University</br>
Eric Zeemering, Northern Illinois University

### Remarks on the Legacy of Deil Wright
Kim Nelson, University of North Carolina at Chapel Hill

 
### The Position of Local Governments in the U.S. Federal System
9:00 AM – 10:30 AM 

#### Municipal Government and its Role in a State-Local System: Evidence from Panel Data
Agustin Leon-Moreta, University of New Mexico

#### Do State Spending Priorities Constrain or Promote Local Government Sustainability Policies?
Jayce L. Farmer, University of Nevada, Las Vegas

#### Power, Protest, and Participation: Understanding the Municipal Takeover of Flint, Michigan
Ashley E. Nickles, Kent State University

#### Do Local Governments with Higher Citizen Ratings on Service Quality Have Higher Service Performance Transparency? Evidence from U.S. Local Governments
Jie Tao, University of North Texas and Brian K. Collins, University of North Texas

### Morning Break
10:30 AM – 10:45 AM

### Audience Discussion: Fifty State Profiles on State-Local Relations
10:45 AM – 11:00 AM 

### A New Look at State Preemption
11:00 AM – 12:15 PM

John Kincaid, Lafayette College Moderator
 
#### State Preemption and the Ghost of Judge Dillon
David Swindell, Arizona State University, Carl Stenberg, University of North Carolina at Chapel Hill, James Svara, University of North Carolina at Chapel Hill

#### Diffusion Quarantine: The Use of State Preemption to Prevent the Spread of Innovations
Daniel J. Mallinson, Penn State Harrisburg

#### Municipal Policy and Fracking Discretion in the States
Brian K. Collins, University of North Texas

### Lunch Break
12:15 PM – 1:30 PM

### Rescaling Governance for State-Local Relations: Regional Intergovernmental Organizations
1:30 PM – 3:00 PM
Jen Nelles, City University of New York – Hunter College, Moderator

#### Leading Actors: The Role of Local Elected Officials on Boards of Regional Intergovernmental Organizations
Jay Rickbaugh, University of Pittsburgh

#### RIGOs and Civic Engagement
George W. Dougherty, Jr., University of Pittsburgh

#### Balancing Local and Regional Interests Using Cultural Heuristics
Thomas Skuzinski, Virginia Polytechnic University

#### Modeling State-Local Coordination of Water Quality Management at the Regional Scale for the Lake Champlain Basin
Christopher Koliba, University of Vermont and Patrick Bitterman, University of Vermont

### Panel Discussion: The Shifting Dynamics of State-Local Relations
3:15 PM – 4:15 PM

Irv Halter, Director, Colorado Department of Local Affairs</br>
Cliff Lippard, Executive Director, Tennessee Advisory Commission on Intergovernmental Relations</br>
Doug Linkhart, President, National Civic League

Please check the SIAM website (<www.siam-aspa.net>) for additional confirmed participants.


### Remarks from Mark Wright on Behalf of the Wright Family
4:15 PM – 4:30 PM
 

### Concluding Remarks

Russ Hanson, Indiana University</br>
Eric Zeemering, Northern Illinois University

 

Note: The SIAM Annual Business Meeting is scheduled for 4:45 PM.